
LINKERS=-lmingw32 -lSDL2main -lSDL2
DEFAULT_PARAMS=-IC:\mingw_dev_lib\include\SDL2 -LC:\mingw_dev_lib\lib -w -Wl,-subsystem,windows


all:
	g++ 02_getting_an_image_on_the_screen.cpp $(DEFAULT_PARAMS) $(LINKERS) -o 02_getting_an_image_on_the_screen
